name: run-deno-tests
on: [push, pull_request]
jobs:
    check-generated-parser:
        runs-on: ubuntu-latest
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.5"
            - uses: actions/checkout@master
              with:
                  repository: python/cpython
                  ref: "3.9"
                  path: cpython
            - uses: actions/checkout@master
              with:
                  path: skulpt_parser
            - run: cd skulpt_parser
            - run: ls -laR
            # - run: git clone https://github.com/python/cpython.git --branch 3.9
            - run: deno install -qAn vr https://deno.land/x/velociraptor@1.0.1/cli.ts
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - run: vr gen_parser
            - run: git diff-index --quiet --cached HEAD --
            - run: vr test
