name: run-deno-tests
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
            - locked
            - unlocked
    push:
        branches:
            - master
jobs:
    check-generated-parser:
        runs-on: ubuntu-latest
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: jurassiscripts/setup-velociraptor@v1
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.5"
            - uses: actions/checkout@master
              with:
                  repository: python/cpython
                  ref: "v3.9.5"
                  path: cpython
            - uses: actions/checkout@master
              with:
                  path: skulpt_parser
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - run: pip install --user pre-commit
            - name: build parser
              run: vr gen_parser
              working-directory: "./skulpt_parser"
            - name: assert clean repo
              run: git diff-index --quiet --cached HEAD --
              working-directory: "./skulpt_parser"
    run-ast-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: jurassiscripts/setup-velociraptor@v1
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.5"
            - uses: actions/checkout@master
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - name: run tests
              run: vr test
              # working-directory: "./skulpt_parser"
    run-parse-tests:
        runs-on: ubuntu-latest
        outputs:
            tests: ${{ steps.run-tests.outputs.test }}
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: jurassiscripts/setup-velociraptor@v1
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.5"
            - uses: actions/checkout@master
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - name: run tests
              id: run-tests
              run: |
                  vr test parse > results
                  echo "::set-output name=results::$(cat results)"
            - name: log last 10 lines
              run: |
                  echo "${{steps.run-tests.outputs.results}}" | tail -n 10
